#Load in Numpy(Numerical Python)

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3],dtype='int32')
print(a)


[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# Get dimesion
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Get shape of numpy array
b.shape

(2, 3)

In [8]:
a.shape

(3,)

In [9]:
# Get type
a.dtype

dtype('int32')

In [10]:
# get size
a.itemsize


4

In [11]:
# get total size
a.nbytes

12

In [12]:
b.nbytes

24

In [13]:
# Accessing/changing specific elements,rows,columns,etc


In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a.shape

(2, 7)

In [16]:
# get a specific element [row,col]
# need to grab 13 say
a[1,5]

13

In [17]:
a[0,0]

1

In [18]:
a[1,2]

10

In [19]:
# get a specific row
a[0,:] 

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [21]:
# get a specific column
a[:,2]

array([ 3, 10])

In [22]:
# getting a littler more fancy [fixrow,startindex:endindex:stepsize]
a[0,0:7:2]

array([1, 3, 5, 7])

In [23]:
a[1,1:4:1]

array([ 9, 10, 11])

In [24]:
a[1,0:-1:1]
# basically
# python supports “indexing from the end”, that is, negative indexing. This means the last value of a sequence has an index of -1, the second last -2, and so on

array([ 8,  9, 10, 11, 12, 13])

In [25]:
# to change value in the array
# for that target the array and reassign some new value
a[1,5] = 20

In [26]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
a[:,2] = 5

In [28]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [29]:
# 3-d example
b = np.array([[[1,2,10],[3,4,11]],[[5,6,12],[7,8,13]]])
b.shape

(2, 2, 3)

In [30]:
print(b)

[[[ 1  2 10]
  [ 3  4 11]]

 [[ 5  6 12]
  [ 7  8 13]]]


In [31]:
# getting specific elem
b[0,0,1]

2

In [32]:
b[1,1,1]

8

In [33]:
b[1,1,2]

13

In [34]:
# getting full rows/col
b[:,1,1]
b[:,:,:]
b[0,1,:]

array([ 3,  4, 11])

In [35]:
# replacing elements
b[0,0,:] = [111,222,333]

In [36]:
print(b)

[[[111 222 333]
  [  3   4  11]]

 [[  5   6  12]
  [  7   8  13]]]


In [37]:
# Initializing different types of arrays
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [38]:
# All 1s matrix
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
# Any random matrix
np.full((2,2),12)

array([[12, 12],
       [12, 12]])

In [40]:
np.full(3,3)

array([3, 3, 3])

In [42]:
# Random decimal numbers
np.random.rand(2,2)

array([[0.7508739 , 0.2053272 ],
       [0.00537852, 0.15792774]])

In [49]:
# Randome integer values
np.random.randint(5,size=(3,3))
# baiscally here syntax is np.random.rand(starting value or the number upto which the matrix will contain that number say:5 then the matrix will contain numbes upto 4 ,size=(x,y))

array([[1, 0, 3],
       [3, 3, 0],
       [3, 0, 4]])

In [50]:
# Printing identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# how to repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [53]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [62]:
output=  np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
output[1,1:4:1] = [0,0,0]
output[1:4:1,1] = [0,0,0]
output[3,1:4:1] = [0,0,0]
output[1:4:1,3] = [0,0,0]
output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
# Another method to print this matrix out of ones
output2 = np.ones((5,5))
print(output2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
z= np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [74]:
output2[1:4,1:4] = z
# or output2[1:-1,1:-1] = z (negative indexing)
print(output2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
# Copying array

a = np.array([1,2,3])
b = a.copy()
print(b)

[1 2 3]


In [78]:
# Mathematics
a = np.array([1,2,3])
a += 3
print(a)

[4 5 6]


In [80]:
a/2
a*2



array([ 8, 10, 12])

In [81]:
print(a)

[4 5 6]


In [83]:
np.sin(a)

array([-0.7568025 , -0.95892427, -0.2794155 ])

In [84]:
np.cos(a)

array([-0.65364362,  0.28366219,  0.96017029])

In [101]:
# Linear ALgebra
# Matrix multiplication
# Make sure the the no.of rows of a should be equal to no.of columns

a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [102]:
b = np.full((2,3),2)
print(b)

[[2 2 2]
 [2 2 2]]


In [104]:
c = np.matmul(a,b)

In [106]:
# Finding the det matrix
np.linalg.det(c)

0.0

In [107]:
"""
Det
trace
singular vector decomposition
eigenvalues
matrix norm
inverse
etc...
"""

'\nDet\ntrace\nsingular vector decomposition\neigenvalues\nmatrix norm\ninverse\netc...\n'

# Statistics


In [119]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
np.min(stats,axis=0)

array([1, 2, 3])

In [121]:
np.max(stats,axis=1)

array([3, 6])

In [122]:
np.sum(stats)

21

# Reorganizing Arrays

In [125]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)