#Load in Numpy(Numerical Python)

In [1]:
import numpy as np

In [31]:
a = np.array([1,2,3],dtype='int32')
print(a)


[1 2 3]


In [32]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [33]:
# Get dimesion
a.ndim

1

In [34]:
b.ndim

2

In [35]:
# Get shape of numpy array
b.shape

(2, 3)

In [36]:
a.shape

(3,)

In [37]:
# Get type
a.dtype

dtype('int32')

In [38]:
# get size
a.itemsize


4

In [39]:
# get total size
a.nbytes

12

In [40]:
b.nbytes

24

In [41]:
# Accessing/changing specific elements,rows,columns,etc


In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
a.shape

(2, 7)

In [44]:
# get a specific element [row,col]
# need to grab 13 say
a[1,5]

13

In [45]:
a[0,0]

1

In [46]:
a[1,2]

10

In [47]:
# get a specific row
a[0,:] 

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [49]:
# get a specific column
a[:,2]

array([ 3, 10])

In [55]:
# getting a littler more fancy [fixrow,startindex:endindex:stepsize]
a[0,0:7:2]

array([1, 3, 5, 7])

In [56]:
a[1,1:4:1]

array([ 9, 10, 11])

In [58]:
a[1,0:-1:1]
# basically
# python supports “indexing from the end”, that is, negative indexing. This means the last value of a sequence has an index of -1, the second last -2, and so on

array([ 8,  9, 10, 11, 12, 13])

In [60]:
# to change value in the array
# for that target the array and reassign some new value
a[1,5] = 20

In [61]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [62]:
a[:,2] = 5

In [63]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [68]:
# 3-d example
b = np.array([[[1,2,10],[3,4,11]],[[5,6,12],[7,8,13]]])
b.shape

(2, 2, 3)

In [69]:
print(b)

[[[ 1  2 10]
  [ 3  4 11]]

 [[ 5  6 12]
  [ 7  8 13]]]


In [71]:
# getting specific elem
b[0,0,1]

2

In [72]:
b[1,1,1]

8

In [73]:
b[1,1,2]

13

In [76]:
# getting full rows/col
b[:,1,1]
b[:,:,:]
b[0,1,:]

array([ 3,  4, 11])

In [78]:
# replacing elements
b[0,0,:] = [111,222,333]

In [79]:
print(b)

[[[111 222 333]
  [  3   4  11]]

 [[  5   6  12]
  [  7   8  13]]]
